version: "3.9"
services:
  web:
    build: .
    command: ./wait-for-it.sh redis:6379 -- ./docker-entrypoint.sh
    ports:
      - 8000:8000
    depends_on:
      - redis
    restart: on-failure
    volumes:
      - .:/app

  redis:
    image: redis:6.2-alpine
    ports:
      - 6379:6379
    restart: always
    volumes:
      - redisdata:/data

  celery:
    build: .
    command: ./wait-for-it.sh redis:6379 -- celery -A account_service worker --loglevel=info
    depends_on:
      - redis
    volumes:
      - .:/app

  celery-beat:
    build: .
    command: ./wait-for-it.sh redis:6379 -- celery -A account_service beat --loglevel=info
    depends_on:
      - redis
    volumes:
      - .:/app

  flower:
    build: .
    command: ./wait-for-it.sh redis:6379 -- celery -A account_service flower
    depends_on:
      - web
      - redis
      - celery
    environment:
      - DEBUG=1
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    ports:
      - 5555:5555

  # tests:
  #   build: .
  #   command: ./wait-for-it.sh redis:6379 -- ptw
  #   depends_on:
  #     - redis
  #   tty: true
  #   volumes:
  #     - .:/app

volumes:
  redisdata:
